version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: arsen
      POSTGRES_PASSWORD: root
      POSTGRES_DB: webapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U arsen"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: always
    environment:
      NODE_ENV: production
      DB_USERNAME: arsen
      DB_PASSWORD: root
      DB_NAME: webapp
      DB_HOST: db
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
